### ISSUE TITLE
let data = frames.shift().split(',') doesn't work

### ISSUE THREAD

**Issue by SevenworksDev** [SpeckyYT/ANMT#1]
Error: Use of undefined member
    ╭─[index.spwn:3:1]
    │
  3 │ ╭─> ANMT(
  5 │ ├─> )
    · │
    · ╰─────── 1: Error comes from this macro call
    │
    ├─[lib.spwn:26:16]
    │
 26 │     let data = frames.shift().split(',')
    ·                ────────────┬────────────
    ·                            ╰────────────── 2: 'split' is undefined
────╯

**Comment by SpeckyYT** [comment]
could you provide more context? (like file input, etc)

**Comment by SevenworksDev** [comment]
frames.shift().split(',') is undefined at lib.spwn and ANMT is an undefined member on index.spwn

**Comment by SpeckyYT** [comment]
I'm unable to reproduce, but probably you're using the `0.7` version of spwn, instead of the `0.7-fix` one, or directly use the master branch of spwn.

**Comment by SpeckyYT** [comment]
Closed for inactivity
