### ISSUE TITLE
Error: Couldn't find module file (./lib\../pckp_libraries/canvas)

### ISSUE THREAD

**Issue by pundang** [SpeckyYT/ANMT#10]
Im getting this error when i try to build the level
![image](https://user-images.githubusercontent.com/40328573/182265874-60118d54-fdb0-4cb2-85c2-8d67c8d48317.png)

**Comment by SpeckyYT** [comment]
You'll have to uncomment the dependencies in `pckp.yaml` https://github.com/SpeckyYT/ANMT/blob/master/pckp.yaml#L9-L10

PCKP is kinda broken on windows (on v0.8) so that's why I commented those out.

**Comment by nachitodev** [comment]
I tried that and this error comes out.
```
C:\Users\Nacho\Downloads\ANMT-master>spwn build example.spwn --allow readfile
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: PermissionDenied, message: "Acceso denegado. (os error 5)" }', pckp\src\package.rs:145:47
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
I also tried running as Administrator and Other Things (downgrading SPWN and changing some code) and nothing works.
Cargo Version: cargo 1.62.0 (a748cf5a3 2022-06-08)
FFMPEG Version: ffmpeg version 5.1-full_build
SPWN: 0.8 (Beta)
Windows Version: Windows 10 Pro x64 21H2 19044.1288

**Comment by SpeckyYT** [comment]
This happens because pckp is bugged on Windows, the best way to get out of this problem is to delete `pckp_tmp/` folder, comment one module (in `pckp.yaml`), run spwn, delete the folder again, uncomment the previous module and comment the other one, and rerun spwn, after this, comment both modules and you're good to go.

**Comment by nachitodev** [comment]
Works now! Thanks u <3
