### ISSUE TITLE
i cnat complite a video to frames

### ISSUE THREAD

**Issue by Rafa69420** [SpeckyYT/ANMT#11]
i have all intslled but i cant 
![Captura de ecrã 2023-02-19 101033](https://user-images.githubusercontent.com/125797138/219941735-00803ef2-3147-4a4b-a536-8b117bad600e.png)

**Comment by SpeckyYT** [comment]
You need to run `anmt "your video file.mp4"`

**Comment by Rafa69420** [comment]
> You need to run `anmt "your video file.mp4"`

is say 'anmt' is not recognized as an internal or external command,
operable program or batch file.
![Captura de ecrã 2023-02-19 203803](https://user-images.githubusercontent.com/125797138/219973896-2ab84c01-2594-4905-862f-3119c0d72e26.png)

**Comment by SpeckyYT** [comment]
ah, you're compiling it from source... then do `cargo run --release "your file.mp4"`

**Comment by Rafa69420** [comment]
> ah, you're compiling it from source... then do `cargo run --release "your file.mp4"`

THANK YOU SO MUCH

**Comment by Rafa69420** [comment]
now apper 


Built in 1 seconds!
0 objects added

Level:

Writing back to savefile...
Writing to level: south park intro
Written to save. You can now open Geometry Dash again!
![Captura de ecrã 2023-02-19 211445](https://user-images.githubusercontent.com/125797138/219975600-d5584298-2ea7-46eb-b46e-63732d29486f.png)
