### ISSUE TITLE
Error: Couldn't find module file (./lib../pckp_libraries/canvas)

### ISSUE THREAD

**Issue by Rafa69420** [SpeckyYT/ANMT#12]
not this error

**Comment by Rafa69420** [comment]
now gives error Parsing ...
Reading savefile...
Building script ...
———————————————————————————

Error: Couldn't find module file (./lib\../pckp_libraries/canvas)
   ╭─[example.spwn:1:1]
   │
 1 │ import './lib/'
   · ───────┬───────
   ·        ╰───────── Error when running this library/module
───╯

C:\Users\Asus\Downloads\ANMT-master\ANMT-master>
![imagem_2023-02-19_220344790](https://user-images.githubusercontent.com/125797138/219977809-ee8af9da-15d4-4205-91ab-fa7618cd4e55.png)

**Comment by Rafa69420** [comment]
and there folder 
![imagem_2023-02-19_220746113](https://user-images.githubusercontent.com/125797138/219977954-8fbbf5b5-76c8-43b6-979e-6acc725512ee.png)

**Comment by Rafa69420** [comment]
and other
![imagem_2023-02-19_220815025](https://user-images.githubusercontent.com/125797138/219977975-5585b39c-fafc-4458-89ce-810d7285177d.png)

**Comment by Rafa69420** [comment]
HELP ME @SpeckyYT

**Comment by SpeckyYT** [comment]
Follow this exactly:

1) in `pckp.yaml`, remove the # on "dependencies"
2) also remove the # on the first "url"
3) run `spwn build example.spwn`
4) delete the `pckp_temp` folder that got generated
5) add # to the first url
6) remove # from the second url
7) run `spwn build example.spwm`
8) add # on dependencies
9) add # on the second url

**Comment by Rafa69420** [comment]
what?? 
![imagem_2023-02-20_101732911](https://user-images.githubusercontent.com/125797138/220077438-db7be260-805b-4007-830c-4ed2d1f53494.png)
![Captura de ecrã 2023-02-20 101701](https://user-images.githubusercontent.com/125797138/220077483-574852f7-b9b2-4652-abee-a2ccf426627a.png)

**Comment by Rafa69420** [comment]
@SpeckyYT

**Comment by SpeckyYT** [comment]
As the error says, you need to do `spwn build example.spwn --allow readfile`

**Comment by Rafa69420** [comment]
@SpeckyYT now appeter this 
![imagem_2023-02-20_122551194](https://user-images.githubusercontent.com/125797138/220106821-83cb91ef-6899-4a96-9df3-4cb2d381be93.png)

**Comment by SpeckyYT** [comment]
there is an indentation before `dependencies`, remove that

**Comment by Rafa69420** [comment]
![imagem_2023-02-20_122922107](https://user-images.githubusercontent.com/125797138/220107937-8b8917b2-e2c9-45d5-a2e1-bab7f48f9104.png)
@SpeckyYT

**Comment by SpeckyYT** [comment]
you didn't save

**Comment by Rafa69420** [comment]
i did all steps @SpeckyYT 
![imagem_2023-02-20_123336643](https://user-images.githubusercontent.com/125797138/220109049-728e9e8e-5854-4b41-993a-0905e7ded4d5.png)

**Comment by SpeckyYT** [comment]
did you change the path/filename in example.spwn to the .txt output?

**Comment by Rafa69420** [comment]
@SpeckyYT i dont understand

**Comment by Rafa69420** [comment]
@SpeckyYT 
![imagem_2023-02-20_123750773](https://user-images.githubusercontent.com/125797138/220109848-35081346-e32c-44e7-ace3-29dc9e6e345b.png)

**Comment by SpeckyYT** [comment]
line 6 in example.spwn,
```
filename = './videos/output/file.txt',
```
change the string to the path of your output `.txt` file

**Comment by Rafa69420** [comment]
i dont have output @SpeckyYT 
![imagem_2023-02-20_123928708](https://user-images.githubusercontent.com/125797138/220110196-65b9406c-1b87-4c37-88e5-73f80e7b2609.png)

**Comment by SpeckyYT** [comment]
the `.txt` file

**Comment by SpeckyYT** [comment]
`'./videos/iShowSpeed Gets Jump Scared Reacting To Clips.txt'`

**Comment by Rafa69420** [comment]
@SpeckyYT like this 
![imagem_2023-02-20_124134615](https://user-images.githubusercontent.com/125797138/220110950-46947f67-e1a1-4105-9711-5221d1c40be4.png)

**Comment by Rafa69420** [comment]
my_video = @ANMT::new(
    filename = './videos/iShowSpeed Gets Jump Scared Reacting To Clips.txt',
    x = -120,
    y = 30,
    scaling = 0.3,
    repeatable = false,
    use_lookup = true,
    use_groups = false, // uses groups instead of color channels for canvas
    groups = [screen],
)

**Comment by SpeckyYT** [comment]
you need to save

**Comment by itsmebombie** [comment]
the world if discord

**Comment by Rafa69420** [comment]
@SpeckyYT it not apper in level
![imagem_2023-02-20_133110359](https://user-images.githubusercontent.com/125797138/220121891-147b9416-0a38-487b-a67e-672b183dab0d.png)

**Comment by SpeckyYT** [comment]
close gd entirely, then build the script, and when it finished completely (the green text saying that you can open gd), then open gd

**Comment by SpeckyYT** [comment]
I assume it's functional, so I'll close this issue, reopen this issue if needed.
