### ISSUE TITLE
Okay what the hell is going on here

### ISSUE THREAD

**Issue by thomasb20** [SpeckyYT/ANMT#15]
So I ran `cargo run --release "vid.mp4"` in the ANMT-master folder and it installed all the stuff needed, but then it came with this issue after trying to run anmt.exe:
![image](https://github.com/SpeckyYT/ANMT/assets/77622308/7aa8899c-21bc-4799-b23d-c370185aeccd)

How do I fix this issue?

**Comment by SpeckyYT** [comment]
This means that `vid.mp4` isn't in the root folder where you're running `cargo run` from.

**Comment by SpeckyYT** [comment]
Closed due to inactivity
