### ISSUE TITLE
error: process didn't exit successfully: `target\release\anmt.exe` (exit code: 2) (previously: error: linker `link.exe` not found   |   = note: program not found)

### ISSUE THREAD

**Issue by yeslol69** [SpeckyYT/ANMT#16]
Updating crates.io index
  Downloaded adler v1.0.2
  Downloaded num-integer v0.1.45
  Downloaded adler32 v1.2.0
  Downloaded color_quant v1.1.0
  Downloaded winapi-util v0.1.5
  Downloaded threadpool v1.8.1
  Downloaded unicode-ident v1.0.1
  Downloaded weezl v0.1.6
  Downloaded serde v1.0.138
  Downloaded rayon-core v1.9.3
  Downloaded crossbeam-channel v0.5.5
  Downloaded num-traits v0.2.15
  Downloaded serde_json v1.0.82
  Downloaded rayon v1.5.3
  Downloaded miniz_oxide v0.5.3
  Downloaded indexmap v1.9.1
  Downloaded image v0.24.2
  Downloaded syn v1.0.98
  Downloaded half v1.8.2
  Downloaded flate2 v1.0.24
  Downloaded crossbeam-epoch v0.9.9
  Downloaded textwrap v0.15.0
  Downloaded serde_derive v1.0.138
  Downloaded ryu v1.0.10
  Downloaded pin-project v1.0.11
  Downloaded lock_api v0.4.7
  Downloaded getrandom v0.2.7
  Downloaded crossbeam-utils v0.8.10
  Downloaded termcolor v1.1.3
  Downloaded spin v0.9.3
  Downloaded gif v0.11.4
  Downloaded smallvec v1.9.0
  Downloaded winapi v0.3.9
  Downloaded jpeg-decoder v0.2.6
  Downloaded scoped_threadpool v0.1.9
  Downloaded ffprobe v0.3.2
  Downloaded bit_field v0.10.1
  Downloaded lebe v0.5.1
  Downloaded bytemuck v1.10.0
  Downloaded flume v0.10.13
  Downloaded png v0.17.5
  Downloaded deflate v1.0.0
  Downloaded json v0.12.4
  Downloaded either v1.7.0
  Downloaded clap v3.2.8
  Downloaded exr v1.4.2
  Downloaded inflate v0.4.5
  Downloaded tiff v0.7.2
  Downloaded proc-macro2 v1.0.40
  Downloaded pin-project-internal v1.0.11
  Downloaded hashbrown v0.12.1
  Downloaded scopeguard v1.1.0
  Downloaded quote v1.0.20
  Downloaded os_str_bytes v6.1.0
  Downloaded once_cell v1.12.0
  Downloaded num_cpus v1.13.1
  Downloaded num-rational v0.4.1
  Downloaded itoa v1.0.2
  Downloaded futures-core v0.3.21
  Downloaded crossbeam-deque v0.8.1
  Downloaded crc32fast v1.3.2
  Downloaded bitflags v1.3.2
  Downloaded strsim v0.10.0
  Downloaded num-iter v0.1.43
  Downloaded nanorand v0.7.0
  Downloaded memoffset v0.6.5
  Downloaded futures-sink v0.3.21
  Downloaded clap_lex v0.2.4
  Downloaded cfg-if v1.0.0
  Downloaded byteorder v1.4.3
  Downloaded autocfg v1.1.0
  Downloaded atty v0.2.14
  Downloaded 72 crates (7.3 MB) in 2.29s (largest was `tiff` at 1.4 MB)
   Compiling autocfg v1.1.0
   Compiling cfg-if v1.0.0
   Compiling proc-macro2 v1.0.40
   Compiling unicode-ident v1.0.1
   Compiling quote v1.0.20
   Compiling syn v1.0.98
   Compiling scopeguard v1.1.0
   Compiling crossbeam-utils v0.8.10
   Compiling once_cell v1.12.0
   Compiling num_cpus v1.13.1
   Compiling rayon-core v1.9.3
error: linker `link.exe` not found
  |
  = note: program not found

note: the msvc targets depend on the msvc linker but `link.exe` was not found

note: please ensure that Visual Studio 2017 or later, or Build Tools for Visual Studio were installed with the Visual C++ option.

note: VS Code is a different product, and is not sufficient.

error: could not compile `quote` (build script) due to previous error
warning: build failed, waiting for other jobs to finish...
error: could not compile `rayon-core` (build script) due to previous error
error: could not compile `crossbeam-utils` (build script) due to previous error
error: could not compile `syn` (build script) due to previous error
error: could not compile `proc-macro2` (build script) due to previous error

how to fix?

**Comment by yeslol69** [comment]
update: I installed Windows SDK and MSVC v142 - VS 2019 C++ x64/x86 build tools from VS 2019 and now it's giving me this error: 

   Compiling proc-macro2 v1.0.40
   Compiling quote v1.0.20
   Compiling syn v1.0.98
   Compiling crossbeam-utils v0.8.10
   Compiling memoffset v0.6.5
   Compiling crossbeam-epoch v0.9.9
   Compiling rayon-core v1.9.3
   Compiling lock_api v0.4.7
   Compiling num-traits v0.2.15
   Compiling winapi v0.3.9
   Compiling crc32fast v1.3.2
   Compiling rayon v1.5.3
   Compiling num-integer v0.1.45
   Compiling futures-core v0.3.21
   Compiling serde_derive v1.0.138
   Compiling adler v1.0.2
   Compiling crossbeam-channel v0.5.5
   Compiling adler32 v1.2.0
   Compiling crossbeam-deque v0.8.1
   Compiling miniz_oxide v0.5.3
   Compiling getrandom v0.2.7
   Compiling serde v1.0.138
   Compiling either v1.7.0
   Compiling spin v0.9.3
   Compiling nanorand v0.7.0
   Compiling deflate v1.0.0
   Compiling num-rational v0.4.1
   Compiling num-iter v0.1.43
   Compiling indexmap v1.9.1
   Compiling bitflags v1.3.2
   Compiling weezl v0.1.6
   Compiling serde_json v1.0.82
   Compiling futures-sink v0.3.21
   Compiling winapi-util v0.1.5
   Compiling flate2 v1.0.24
   Compiling inflate v0.4.5
   Compiling threadpool v1.8.1
   Compiling itoa v1.0.2
   Compiling jpeg-decoder v0.2.6
   Compiling smallvec v1.9.0
   Compiling hashbrown v0.12.1
   Compiling lebe v0.5.1
   Compiling half v1.8.2
   Compiling bit_field v0.10.1
   Compiling ryu v1.0.10
   Compiling color_quant v1.1.0
   Compiling os_str_bytes v6.1.0
   Compiling clap_lex v0.2.4
   Compiling gif v0.11.4
   Compiling tiff v0.7.2
   Compiling termcolor v1.1.3
   Compiling pin-project-internal v1.0.11
   Compiling png v0.17.5
   Compiling atty v0.2.14
   Compiling textwrap v0.15.0
   Compiling pin-project v1.0.11
   Compiling scoped_threadpool v0.1.9
   Compiling flume v0.10.13
   Compiling exr v1.4.2
   Compiling byteorder v1.4.3
   Compiling bytemuck v1.10.0
   Compiling strsim v0.10.0
   Compiling json v0.12.4
   Compiling clap v3.2.8
   Compiling image v0.24.2
   Compiling ffprobe v0.3.2
   Compiling anmt v0.0.1 (C:\Users\mlgda\Desktop\ANMT-master)
    Finished release [optimized] target(s) in 49.46s
     Running `target\release\anmt.exe`
ANMT

USAGE:
    anmt.exe [OPTIONS] <VIDEO_FILE>

ARGS:
    <VIDEO_FILE>    Video file to process

OPTIONS:
    -b, --bits [<bits>...]
            Color precision (1-8) (8 is best)

    -e, --skip_extract
            Skip extraction

    -f, --filter [<filter>...]
            Filter the video (nearest, linear, cubic, gaussian, lanczos3)

    -h, --help
            Print help information

    -o, --optimize [<optimization>...]
            Optimize the video (none, forward, backward, both)

    -p, --pixels [<pixels>...]
            Maximum number of pixels to output

    -q, --quiet
            Don't print anything
error: process didn't exit successfully: `target\release\anmt.exe` (exit code: 2)

**Comment by SpeckyYT** [comment]
It's all working as intended, if you read all of the options you can input your video and preprocess it.

**Comment by SpeckyYT** [comment]
Closed for inactivity
