### ISSUE TITLE
What does the name mean?

### ISSUE THREAD

**Issue by slashglooby** [SpeckyYT/ANMT#17]
Like, spwn is "spwn" because the spawn trigger so like, what...

**Comment by SpeckyYT** [comment]
Exactly, it means nothing else.

The SPWN naming convention is `take a trigger's name, keep the first letter, remove all vowels, and make it uppercase`.

e.g.:
```
ANMT (ANiMaTe)
FLLW (FoLLoW)
FLWPLRY (FoLloW PLayeR Y) (some characters were removed to not make it too long)
SHW (SHoW)
etc
```
