### ISSUE TITLE
scaling is not defined

### ISSUE THREAD

**Issue by noah-kl** [SpeckyYT/ANMT#2]
![image](https://user-images.githubusercontent.com/72023323/136680226-46315d45-85ae-437c-8689-583750308bc6.png)
what does this mena

**Comment by SpeckyYT** [comment]
Whoops, there was a bug in `spwn-canvas` where I wrote `scale` instead of `scaling`. It should be fixed in the latest commit.

**Comment by noah-kl** [comment]
everything works now, thanks
