### ISSUE TITLE
program creates the png photos, but there's no output file and txt file

### ISSUE THREAD

**Issue by ut422** [SpeckyYT/ANMT#20]
![Screenshot (306)](https://github.com/SpeckyYT/ANMT/assets/58406210/71167016-d8f7-4fe6-a0fd-299a90364ea2)
![Screenshot (305)](https://github.com/SpeckyYT/ANMT/assets/58406210/f0d7b99c-3e22-4906-8380-045d32885dae)
I'm using nodejs version v16.16.0 and ffmpeg version 2023-11-22-git-0008e1c5d5-full_build-www.gyan.dev
ffmpeg is added to PATH

**Comment by SpeckyYT** [comment]
You also need ffprobe, but I assume you already solved this issue or you gave up on it.
