### ISSUE TITLE
help

### ISSUE THREAD

**Issue by awppin** [SpeckyYT/ANMT#23]
Finished release [optimized] target(s) in 0.21s
     Running `target\release\anmt.exe`
ANMT

USAGE:
    anmt.exe [OPTIONS] <VIDEO_FILE>

ARGS:
    <VIDEO_FILE>    Video file to process

OPTIONS:
    -b, --bits [<bits>...]
            Color precision (1-8) (8 is best)

    -e, --skip_extract
            Skip extraction

    -f, --filter [<filter>...]
            Filter the video (nearest, linear, cubic, gaussian, lanczos3)

    -h, --help
            Print help information

    -o, --optimize [<optimization>...]
            Optimize the video (none, forward, backward, both)

    -p, --pixels [<pixels>...]
            Maximum number of pixels to output

    -q, --quiet
            Don't print anything
error: process didn't exit successfully: `target\release\anmt.exe` (exit code: 2)

I dont know what any of this means and there is nothing on google

was i supposted to use the absolute version of ffmpeg? aka https://github.com/absolllute/ffmpeg-build

**Comment by SpeckyYT** [comment]
The help message exactly tells you how to use it. Also, the README says everything you need to do for ffmpeg to work, you don't have to rely on something that has nothing to do with this project.
