### ISSUE TITLE
The .txt file and the output folder are not created.

### ISSUE THREAD

**Issue by nachitodev** [SpeckyYT/ANMT#3]
### 2 Errors:
![imagen](https://user-images.githubusercontent.com/67612701/143174325-76c69f08-18e3-41c9-8dd5-fa02ea228b7d.png)
### Videos Folder with no output folder.
![imagen](https://user-images.githubusercontent.com/67612701/143174534-26b6fc07-d36d-498c-ae68-8e43ddb2894a.png)
### Second try (Only Proccesing) also with not success.
![imagen](https://user-images.githubusercontent.com/67612701/143174672-94e5de5f-fcce-4b54-901f-2e580b910efe.png)

**Comment by nachitodev** [comment]
Im using ffmpeg version n4.4.1-2-gcc33e73618-20211123 and Node v12.22.1

**Comment by SpeckyYT** [comment]
It's weird the fact that ffmpeg's stdout doesn't get printed to the terminal for you.
Could you try to update node to v16 or something to see if it changes anything?

I also used to get that `pnglib error` while development, but it magically disappeared, so idk

About the last image.... that's really weird that it yeets itself and doesn't throw an error.

Yeah, try to update nodejs and see what happens.

**Comment by SpeckyYT** [comment]
Closed for inactivity, reopen the issue if you're continuing to have these same issues.
